[package]
name = "plant-cam"
version = "0.1.0"
authors = ["Eric Mikulin <ericm99@gmail.com>"]
edition = "2018"

[dependencies]
clokwerk = "0.3"
warp = "0.3"

[dependencies.tokio]
features = ["full"]
version = "1.1"

[dependencies.uuid]
features = ["v4"]
version = "0.8"
